### PR TITLE
More precise install instructions

### PR DESCRIPTION
**Pull request by ZJvandeWeg**

### CODE REVIEW

**Comment by kinow** [comment]
Patches / pull requests welcome :-)

**Comment by ZJvandeWeg** [comment]
@kinow This is a PR 😉

**Comment by tylermauthe** [comment]
Looks good to me! Thanks for the update.

**Comment by kinow** [comment]
Oh, sorry @ZJvandeWeg I hadn't noticed it. And thanks @tylermauthe for merging :)

**Pull request merged**
